export const SERVICE_PAGE_COPY = {
  "saas-development": {
    hero: "SaaS Development.",
    subhead: "Billing, onboarding, and the first paid customer path.",
    metaTitle: "SaaS Development | Futurebits",
    metaDescription: "SaaS Development by Futurebits: billing, onboarding, and the first paid customer path. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "web-app-development": {
    hero: "Web App Development.",
    subhead: "Auth, data model, and the flows users hit daily.",
    metaTitle: "Web App Development | Futurebits",
    metaDescription: "Web App Development by Futurebits: auth, data model, and the flows users hit daily. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "custom-software-development": {
    hero: "Custom Software Development.",
    subhead: "Workflows your off-the-shelf tools cannot model.",
    metaTitle: "Custom Software Development | Futurebits",
    metaDescription: "Custom Software Development by Futurebits: workflows your off-the-shelf tools cannot model. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "mvp-development": {
    hero: "MVP Development.",
    subhead: "One testable hypothesis, not a feature wish list.",
    metaTitle: "MVP Development | Futurebits",
    metaDescription: "MVP Development by Futurebits: one testable hypothesis, not a feature wish list. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "full-stack-development": {
    hero: "Full Stack Development.",
    subhead: "Frontend, API, and deploy in one repo.",
    metaTitle: "Full Stack Development | Futurebits",
    metaDescription: "Full Stack Development by Futurebits: frontend, API, and deploy in one repo. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "frontend-development": {
    hero: "Frontend Development.",
    subhead: "React UI that matches design and passes Core Web Vitals.",
    metaTitle: "Frontend Development | Futurebits",
    metaDescription: "Frontend Development by Futurebits: React UI that matches design and passes Core Web Vitals. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "backend-development": {
    hero: "Backend Development.",
    subhead: "APIs, jobs, and data layers that survive traffic spikes.",
    metaTitle: "Backend Development | Futurebits",
    metaDescription: "Backend Development by Futurebits: APIs, jobs, and data layers that survive traffic spikes. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "api-development": {
    hero: "API Development.",
    subhead: "REST or GraphQL contracts your partners can integrate against.",
    metaTitle: "API Development | Futurebits",
    metaDescription: "API Development by Futurebits: REST or GraphQL contracts your partners can integrate against. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "dashboard-development": {
    hero: "Dashboard Development.",
    subhead: "Role-aware views on data your team already trusts.",
    metaTitle: "Dashboard Development | Futurebits",
    metaDescription: "Dashboard Development by Futurebits: role-aware views on data your team already trusts. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "admin-panel-development": {
    hero: "Admin Panel Development.",
    subhead: "Internal ops screens that replace spreadsheet chaos.",
    metaTitle: "Admin Panel Development | Futurebits",
    metaDescription: "Admin Panel Development by Futurebits: internal ops screens that replace spreadsheet chaos. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "client-portal-development": {
    hero: "Client Portal Development.",
    subhead: "Customer-facing portals with auth and file workflows.",
    metaTitle: "Client Portal Development | Futurebits",
    metaDescription: "Client Portal Development by Futurebits: customer-facing portals with auth and file workflows. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "internal-tool-development": {
    hero: "Internal Tool Development.",
    subhead: "Ops tools that cut hours off weekly manual work.",
    metaTitle: "Internal Tool Development | Futurebits",
    metaDescription: "Internal Tool Development by Futurebits: ops tools that cut hours off weekly manual work. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "crm-development": {
    hero: "CRM Development.",
    subhead: "Pipeline views and automations tied to how you actually sell.",
    metaTitle: "CRM Development | Futurebits",
    metaDescription: "CRM Development by Futurebits: pipeline views and automations tied to how you actually sell. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "marketplace-development": {
    hero: "Marketplace Development.",
    subhead: "Two-sided flows, payouts, and trust mechanics.",
    metaTitle: "Marketplace Development | Futurebits",
    metaDescription: "Marketplace Development by Futurebits: two-sided flows, payouts, and trust mechanics. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "subscription-platform-development": {
    hero: "Subscription Platform Development.",
    subhead: "Plans, trials, and upgrade paths in one codebase.",
    metaTitle: "Subscription Platform Development | Futurebits",
    metaDescription: "Subscription Platform Development by Futurebits: plans, trials, and upgrade paths in one codebase. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "workflow-automation-software": {
    hero: "Workflow Automation Software.",
    subhead: "Repeatable steps your team still handles by hand.",
    metaTitle: "Workflow Automation Software | Futurebits",
    metaDescription: "Workflow Automation Software by Futurebits: repeatable steps your team still handles by hand. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "reporting-platform-development": {
    hero: "Reporting Platform Development.",
    subhead: "Scheduled reports nobody has to rebuild in Excel.",
    metaTitle: "Reporting Platform Development | Futurebits",
    metaDescription: "Reporting Platform Development by Futurebits: scheduled reports nobody has to rebuild in Excel. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "business-process-automation": {
    hero: "Business Process Automation.",
    subhead: "Handoffs between teams that currently live in email.",
    metaTitle: "Business Process Automation | Futurebits",
    metaDescription: "Business Process Automation by Futurebits: handoffs between teams that currently live in email. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "no-code-to-code-migration": {
    hero: "No-Code to Code Migration.",
    subhead: "Bubble or Webflow limits you are hitting at scale.",
    metaTitle: "No-Code to Code Migration | Futurebits",
    metaDescription: "No-Code to Code Migration by Futurebits: Bubble or Webflow limits you are hitting at scale. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "legacy-software-modernization": {
    hero: "Legacy Software Modernization.",
    subhead: "Monoliths that are slow to change and scary to deploy.",
    metaTitle: "Legacy Software Modernization | Futurebits",
    metaDescription: "Legacy Software Modernization by Futurebits: monoliths that are slow to change and scary to deploy. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "excel-automation-smart-reporting": {
    hero: "Excel Automation & Smart Reporting.",
    subhead: "Spreadsheet workflows that eat days every month.",
    metaTitle: "Excel Automation & Smart Reporting | Futurebits",
    metaDescription: "Excel Automation & Smart Reporting by Futurebits: spreadsheet workflows that eat days every month. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-saas-development": {
    hero: "AI SaaS Development.",
    subhead: "AI features inside a SaaS product, not a separate demo app.",
    metaTitle: "AI SaaS Development | Futurebits",
    metaDescription: "AI SaaS Development by Futurebits: AI features inside a SaaS product, not a separate demo app. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-product-development": {
    hero: "AI Product Development.",
    subhead: "Search, recommendations, or agents inside your existing product.",
    metaTitle: "AI Product Development | Futurebits",
    metaDescription: "AI Product Development by Futurebits: search, recommendations, or agents inside your existing product. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-workflow-automation": {
    hero: "AI Workflow Automation.",
    subhead: "LLM steps in ops pipelines with human review where it matters.",
    metaTitle: "AI Workflow Automation | Futurebits",
    metaDescription: "AI Workflow Automation by Futurebits: LLM steps in ops pipelines with human review where it matters. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "chatbot-development": {
    hero: "Chatbot Development.",
    subhead: "Website and support bots with escalation, not infinite intents.",
    metaTitle: "Chatbot Development | Futurebits",
    metaDescription: "Chatbot Development by Futurebits: website and support bots with escalation, not infinite intents. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "rag-application-development": {
    hero: "RAG Application Development.",
    subhead: "Retrieval pipelines with evals on your real documents.",
    metaTitle: "RAG Application Development | Futurebits",
    metaDescription: "RAG Application Development by Futurebits: retrieval pipelines with evals on your real documents. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-document-processing": {
    hero: "AI Document Processing.",
    subhead: "PDFs and forms parsed into structured data you can act on.",
    metaTitle: "AI Document Processing | Futurebits",
    metaDescription: "AI Document Processing by Futurebits: PDFs and forms parsed into structured data you can act on. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-search-systems": {
    hero: "AI Search Systems.",
    subhead: "Semantic search over product docs, tickets, or catalog data.",
    metaTitle: "AI Search Systems | Futurebits",
    metaDescription: "AI Search Systems by Futurebits: semantic search over product docs, tickets, or catalog data. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-recommendation-systems": {
    hero: "AI Recommendation Systems.",
    subhead: "Ranking that uses your data, not generic collaborative filtering.",
    metaTitle: "AI Recommendation Systems | Futurebits",
    metaDescription: "AI Recommendation Systems by Futurebits: ranking that uses your data, not generic collaborative filtering. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-agents-development": {
    hero: "AI Agents Development.",
    subhead: "Agents for sales prep, support triage, or internal ops; scoped.",
    metaTitle: "AI Agents Development | Futurebits",
    metaDescription: "AI Agents Development by Futurebits: agents for sales prep, support triage, or internal ops. scoped. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "llm-integration": {
    hero: "LLM Integration.",
    subhead: "Summarization, classification, or generation inside your app.",
    metaTitle: "LLM Integration | Futurebits",
    metaDescription: "LLM Integration by Futurebits: summarization, classification, or generation inside your app. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "openai-api-integration": {
    hero: "OpenAI API Integration.",
    subhead: "OpenAI calls with fallbacks, logging, and cost controls.",
    metaTitle: "OpenAI API Integration | Futurebits",
    metaDescription: "OpenAI API Integration by Futurebits: OpenAI calls with fallbacks, logging, and cost controls. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "custom-ai-tools": {
    hero: "Custom AI Tools.",
    subhead: "Internal tools your team asks for in Slack every week.",
    metaTitle: "Custom AI Tools | Futurebits",
    metaDescription: "Custom AI Tools by Futurebits: internal tools your team asks for in Slack every week. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-dashboard-development": {
    hero: "AI Dashboard Development.",
    subhead: "Dashboards that surface model quality and usage, not vanity charts.",
    metaTitle: "AI Dashboard Development | Futurebits",
    metaDescription: "AI Dashboard Development by Futurebits: dashboards that surface model quality and usage, not vanity charts. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-data-extraction": {
    hero: "AI-Based Data Extraction.",
    subhead: "Unstructured inputs turned into JSON your systems can ingest.",
    metaTitle: "AI-Based Data Extraction | Futurebits",
    metaDescription: "AI-Based Data Extraction by Futurebits: unstructured inputs turned into JSON your systems can ingest. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-customer-support-tools": {
    hero: "AI Customer Support Tools.",
    subhead: "Deflection on top-20 tickets with Zendesk or Intercom handoff.",
    metaTitle: "AI Customer Support Tools | Futurebits",
    metaDescription: "AI Customer Support Tools by Futurebits: deflection on top-20 tickets with Zendesk or Intercom handoff. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "custom-gpt-knowledge-base": {
    hero: "Custom GPT & Knowledge Base Solutions.",
    subhead: "Custom GPTs grounded in your policies and product docs.",
    metaTitle: "Custom GPT & Knowledge Base Solutions | Futurebits",
    metaDescription: "Custom GPT & Knowledge Base Solutions by Futurebits: Custom GPTs grounded in your policies and product docs. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-content-generation": {
    hero: "AI Content Generation Systems.",
    subhead: "Marketing copy pipelines with tone and fact-check gates.",
    metaTitle: "AI Content Generation Systems | Futurebits",
    metaDescription: "AI Content Generation Systems by Futurebits: marketing copy pipelines with tone and fact-check gates. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ai-video-generation": {
    hero: "AI Video Generation.",
    subhead: "Templated video output for social and ads; brand-locked.",
    metaTitle: "AI Video Generation | Futurebits",
    metaDescription: "AI Video Generation by Futurebits: templated video output for social and ads. brand-locked. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ui-ux-design": {
    hero: "UI/UX Design.",
    subhead: "Flows where users drop off, not decorative screen refreshes.",
    metaTitle: "UI/UX Design | Futurebits",
    metaDescription: "UI/UX Design by Futurebits: flows where users drop off, not decorative screen refreshes. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "product-design": {
    hero: "Product Design.",
    subhead: "Problem framing through shipped UI in Figma and code.",
    metaTitle: "Product Design | Futurebits",
    metaDescription: "Product Design by Futurebits: problem framing through shipped UI in Figma and code. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "web-app-design": {
    hero: "Web App Design.",
    subhead: "Web product UI that engineers can build from components.",
    metaTitle: "Web App Design | Futurebits",
    metaDescription: "Web App Design by Futurebits: web product UI that engineers can build from components. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "saas-ui-design": {
    hero: "SaaS UI Design.",
    subhead: "SaaS patterns for onboarding, settings, and billing screens.",
    metaTitle: "SaaS UI Design | Futurebits",
    metaDescription: "SaaS UI Design by Futurebits: SaaS patterns for onboarding, settings, and billing screens. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "dashboard-ui-design": {
    hero: "Dashboard UI Design.",
    subhead: "Dense data views that stay scannable on a laptop.",
    metaTitle: "Dashboard UI Design | Futurebits",
    metaDescription: "Dashboard UI Design by Futurebits: dense data views that stay scannable on a laptop. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "design-systems": {
    hero: "Design Systems.",
    subhead: "10–15 components your team reuses, not a 200-component library day one.",
    metaTitle: "Design Systems | Futurebits",
    metaDescription: "Design Systems by Futurebits: 10–15 components your team reuses, not a 200-component library day one. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "wireframing": {
    hero: "Wireframing.",
    subhead: "Clickable flows before engineering commits to architecture.",
    metaTitle: "Wireframing | Futurebits",
    metaDescription: "Wireframing by Futurebits: clickable flows before engineering commits to architecture. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "prototyping": {
    hero: "Prototyping.",
    subhead: "Interactive prototypes for stakeholder and user testing.",
    metaTitle: "Prototyping | Futurebits",
    metaDescription: "Prototyping by Futurebits: interactive prototypes for stakeholder and user testing. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "landing-page-design": {
    hero: "Landing Page Design.",
    subhead: "Landing pages matched to your acquisition channel.",
    metaTitle: "Landing Page Design | Futurebits",
    metaDescription: "Landing Page Design by Futurebits: landing pages matched to your acquisition channel. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "mobile-app-ui-design": {
    hero: "Mobile App UI Design.",
    subhead: "Touch-first UI for iOS, Android, or responsive web.",
    metaTitle: "Mobile App UI Design | Futurebits",
    metaDescription: "Mobile App UI Design by Futurebits: touch-first UI for iOS, Android, or responsive web. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "user-flow-design": {
    hero: "User Flow Design.",
    subhead: "Signup-to-activation paths with fewer steps.",
    metaTitle: "User Flow Design | Futurebits",
    metaDescription: "User Flow Design by Futurebits: signup-to-activation paths with fewer steps. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "figma-design": {
    hero: "Figma Design.",
    subhead: "Figma files organized for handoff, not presentation decks.",
    metaTitle: "Figma Design | Futurebits",
    metaDescription: "Figma Design by Futurebits: Figma files organized for handoff, not presentation decks. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "website-ux-audit": {
    hero: "Website UX Audit & Product Experience Audit.",
    subhead: "Conversion blockers on high-intent pages; ranked by impact.",
    metaTitle: "Website UX Audit & Product Experience Audit | Futurebits",
    metaDescription: "Website UX Audit & Product Experience Audit by Futurebits: conversion blockers on high-intent pages. ranked by impact. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "ux-research": {
    hero: "UX Research.",
    subhead: "Five interviews that answer one product decision.",
    metaTitle: "UX Research | Futurebits",
    metaDescription: "UX Research by Futurebits: five interviews that answer one product decision. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "branding-visual-identity": {
    hero: "Branding & Visual Identity.",
    subhead: "Logo, type, and color that work in product UI and marketing, not decks alone.",
    metaTitle: "Branding & Visual Identity | Futurebits",
    metaDescription: "Branding & Visual Identity by Futurebits: logo, type, and color that work in product UI and marketing, not decks alone. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "data-visualization-design": {
    hero: "Data Visualization Design.",
    subhead: "Charts and dashboards that change what teams do Monday morning.",
    metaTitle: "Data Visualization Design | Futurebits",
    metaDescription: "Data Visualization Design by Futurebits: charts and dashboards that change what teams do Monday morning. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "strategy-backtesting": {
    hero: "Strategy Backtesting.",
    subhead: "Backtests with fees, slippage, and fill logic you can defend.",
    metaTitle: "Strategy Backtesting | Futurebits",
    metaDescription: "Strategy Backtesting by Futurebits: backtests with fees, slippage, and fill logic you can defend. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "forward-testing-shadow-mode": {
    hero: "Forward Testing and Shadow Mode.",
    subhead: "Paper and shadow runs before real capital.",
    metaTitle: "Forward Testing & Shadow Mode | Futurebits",
    metaDescription: "Forward Testing & Shadow Mode by Futurebits: paper and shadow runs before real capital. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "live-trading-execution-systems": {
    hero: "Live Trading Execution Systems.",
    subhead: "Order lifecycle, retries, and kill switches in prod.",
    metaTitle: "Live Trading Execution Systems | Futurebits",
    metaDescription: "Live Trading Execution Systems by Futurebits: order lifecycle, retries, and kill switches in prod. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "real-time-pnl-exposure-monitoring": {
    hero: "Real-Time PnL & Exposure Monitoring.",
    subhead: "PnL and exposure alerts before small issues compound.",
    metaTitle: "Real-Time PnL & Exposure Monitoring | Futurebits",
    metaDescription: "Real-Time PnL & Exposure Monitoring by Futurebits: PnL and exposure alerts before small issues compound. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "trade-analytics-reporting": {
    hero: "Trade Analytics & Reporting.",
    subhead: "Slippage and attribution reports your PM actually reads.",
    metaTitle: "Trade Analytics & Reporting | Futurebits",
    metaDescription: "Trade Analytics & Reporting by Futurebits: slippage and attribution reports your PM actually reads. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "quant-research-infrastructure": {
    hero: "Quant Research Infrastructure.",
    subhead: "Research pipelines that reproduce, not one-off notebooks.",
    metaTitle: "Quant Research Infrastructure | Futurebits",
    metaDescription: "Quant Research Infrastructure by Futurebits: research pipelines that reproduce, not one-off notebooks. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "trading-system-audits-consulting": {
    hero: "Trading System Audits & Consulting.",
    subhead: "Architecture and risk review with a fix list owners can execute.",
    metaTitle: "Trading System Audits & Consulting | Futurebits",
    metaDescription: "Trading System Audits & Consulting by Futurebits: architecture and risk review with a fix list owners can execute. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "trading-stack-observability-alerting": {
    hero: "Trading Stack Observability & Alerting.",
    subhead: "Latency, fills, and health metrics with on-call runbooks.",
    metaTitle: "Trading Stack Observability & Alerting | Futurebits",
    metaDescription: "Trading Stack Observability & Alerting by Futurebits: latency, fills, and health metrics with on-call runbooks. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "tradingview-indicators-automation": {
    hero: "TradingView Indicators & Automation.",
    subhead: "TradingView alerts wired to execution or logging safely.",
    metaTitle: "TradingView Indicators & Automation | Futurebits",
    metaDescription: "TradingView Indicators & Automation by Futurebits: TradingView alerts wired to execution or logging safely. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "trading-tech-maintenance-on-call": {
    hero: "Trading Tech Maintenance & On-Call.",
    subhead: "On-call for trading infra without hero engineers.",
    metaTitle: "Trading Tech Maintenance & On-Call | Futurebits",
    metaDescription: "Trading Tech Maintenance & On-Call by Futurebits: on-call for trading infra without hero engineers. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "payment-gateway-integration": {
    hero: "Payment Gateway Integration.",
    subhead: "Checkout flows with reconciliation and error handling.",
    metaTitle: "Payment Gateway Integration | Futurebits",
    metaDescription: "Payment Gateway Integration by Futurebits: checkout flows with reconciliation and error handling. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "stripe-integration": {
    hero: "Stripe Integration.",
    subhead: "Stripe checkout, webhooks, and idempotent handlers.",
    metaTitle: "Stripe Integration | Futurebits",
    metaDescription: "Stripe Integration by Futurebits: Stripe checkout, webhooks, and idempotent handlers. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "razorpay-integration": {
    hero: "Razorpay Integration.",
    subhead: "Razorpay for India; subscriptions and webhooks included.",
    metaTitle: "Razorpay Integration | Futurebits",
    metaDescription: "Razorpay Integration by Futurebits: Razorpay for India. subscriptions and webhooks included. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "subscription-billing-setup": {
    hero: "Subscription Billing Setup.",
    subhead: "Plans, proration, dunning, and finance-visible reporting.",
    metaTitle: "Subscription Billing Setup | Futurebits",
    metaDescription: "Subscription Billing Setup by Futurebits: plans, proration, dunning, and finance-visible reporting. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "crm-integration": {
    hero: "CRM Integration.",
    subhead: "CRM and product data in sync, not duplicate manual entry.",
    metaTitle: "CRM Integration | Futurebits",
    metaDescription: "CRM Integration by Futurebits: CRM and product data in sync, not duplicate manual entry. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "whatsapp-api-integration": {
    hero: "WhatsApp API Integration.",
    subhead: "WhatsApp Business API for notifications and support.",
    metaTitle: "WhatsApp API Integration | Futurebits",
    metaDescription: "WhatsApp API Integration by Futurebits: WhatsApp Business API for notifications and support. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "email-automation-integration": {
    hero: "Email Automation Integration.",
    subhead: "Resend, SendGrid, or Customer.io wired to product events.",
    metaTitle: "Email Automation Integration | Futurebits",
    metaDescription: "Email Automation Integration by Futurebits: Resend, SendGrid, or Customer.io wired to product events. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "google-analytics-setup": {
    hero: "Google Analytics Setup.",
    subhead: "GA4 events that match product metrics, not default pageviews only.",
    metaTitle: "Google Analytics Setup | Futurebits",
    metaDescription: "Google Analytics Setup by Futurebits: GA4 events that match product metrics, not default pageviews only. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "cms-integration": {
    hero: "CMS Integration.",
    subhead: "Headless CMS content in your Next.js or React app.",
    metaTitle: "CMS Integration | Futurebits",
    metaDescription: "CMS Integration by Futurebits: headless CMS content in your Next.js or React app. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "third-party-api-integration": {
    hero: "Third-Party API Integration.",
    subhead: "Vendor APIs with retries, rate limits, and monitoring.",
    metaTitle: "Third-Party API Integration | Futurebits",
    metaDescription: "Third-Party API Integration by Futurebits: vendor APIs with retries, rate limits, and monitoring. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "authentication-setup": {
    hero: "Authentication Setup.",
    subhead: "Auth0, Clerk, or Supabase Auth with RBAC basics.",
    metaTitle: "Authentication Setup | Futurebits",
    metaDescription: "Authentication Setup by Futurebits: Auth0, Clerk, or Supabase Auth with RBAC basics. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "role-based-access-control": {
    hero: "Role-Based Access Control.",
    subhead: "Roles and permissions that match how your org actually works.",
    metaTitle: "Role-Based Access Control | Futurebits",
    metaDescription: "Role-Based Access Control by Futurebits: roles and permissions that match how your org actually works. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "database-setup": {
    hero: "Database Setup.",
    subhead: "Postgres or Supabase schema, migrations, and backup basics.",
    metaTitle: "Database Setup | Futurebits",
    metaDescription: "Database Setup by Futurebits: Postgres or Supabase schema, migrations, and backup basics. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "cloud-deployment": {
    hero: "Cloud Deployment.",
    subhead: "Vercel, AWS, or Railway deploy with env and CI wired.",
    metaTitle: "Cloud Deployment | Futurebits",
    metaDescription: "Cloud Deployment by Futurebits: Vercel, AWS, or Railway deploy with env and CI wired. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "startup-mvp": {
    hero: "Startup MVP.",
    subhead: "First release that tests one business hypothesis.",
    metaTitle: "Startup MVP | Futurebits",
    metaDescription: "Startup MVP by Futurebits: first release that tests one business hypothesis. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "founder-tech-partner": {
    hero: "Founder Tech Partner.",
    subhead: "Technical decisions when you do not have a CTO yet.",
    metaTitle: "Founder Tech Partner | Futurebits",
    metaDescription: "Founder Tech Partner by Futurebits: technical decisions when you do not have a CTO yet. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "product-strategy": {
    hero: "Product Strategy.",
    subhead: "What to build first; ranked by revenue impact.",
    metaTitle: "Product Strategy | Futurebits",
    metaDescription: "Product Strategy by Futurebits: what to build first. ranked by revenue impact. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "product-consulting": {
    hero: "Product Consulting.",
    subhead: "Roadmap and scope review before you hire or spend.",
    metaTitle: "Product Consulting | Futurebits",
    metaDescription: "Product Consulting by Futurebits: roadmap and scope review before you hire or spend. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "tech-consulting": {
    hero: "Tech Consulting.",
    subhead: "Architecture choices without a six-week assessment deck.",
    metaTitle: "Tech Consulting | Futurebits",
    metaDescription: "Tech Consulting by Futurebits: architecture choices without a six-week assessment deck. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "saas-launch-partner": {
    hero: "SaaS Launch Partner.",
    subhead: "Launch checklist: billing, analytics, and onboarding live.",
    metaTitle: "SaaS Launch Partner | Futurebits",
    metaDescription: "SaaS Launch Partner by Futurebits: launch checklist: billing, analytics, and onboarding live. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "prototype-to-product": {
    hero: "Prototype to Product.",
    subhead: "Prototype hardened for real users and real data.",
    metaTitle: "Prototype to Product | Futurebits",
    metaDescription: "Prototype to Product by Futurebits: prototype hardened for real users and real data. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "idea-to-mvp": {
    hero: "Idea to MVP.",
    subhead: "A defined path from idea to working software.",
    metaTitle: "Idea to MVP | Futurebits",
    metaDescription: "Idea to MVP by Futurebits: a defined path from idea to working software. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "product-roadmap-planning": {
    hero: "Product Roadmap Planning.",
    subhead: "Roadmap your team can execute, not a 40-item wish list.",
    metaTitle: "Product Roadmap Planning | Futurebits",
    metaDescription: "Product Roadmap Planning by Futurebits: roadmap your team can execute, not a 40-item wish list. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "software-architecture-planning": {
    hero: "Software Architecture Planning.",
    subhead: "Architecture doc your first three hires can follow.",
    metaTitle: "Software Architecture Planning | Futurebits",
    metaDescription: "Software Architecture Planning by Futurebits: architecture doc your first three hires can follow. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
  "end-to-end-product-design-development": {
    hero: "End-to-End Product Design & Development.",
    subhead: "Design and engineering in one team in one repository.",
    metaTitle: "End-to-End Product Design & Development | Futurebits",
    metaDescription: "End-to-End Product Design & Development by Futurebits: design and engineering in one team. one repo. Scope, dependencies, and acceptance checks are agreed before implementation.",
  },
};

export const MARKETS_AUDIENCE = {
  "strategy-backtesting": {
    dominantPersona: "Quant funds",
    dominantAudience: "Quant funds validating signal stability before allocation reviews.",
    secondaryAudiences: ["Prop desks testing variants across regimes.","Discretionary teams codifying playbooks into testable systems."],
  },
  "forward-testing-shadow-mode": {
    dominantPersona: "Prop desks",
    dominantAudience: "Prop desks pressure-testing intraday systems before desk capital.",
    secondaryAudiences: ["Funds with strict research-to-production gates.","Desks validating model overlays alongside manual execution."],
  },
  "live-trading-execution-systems": {
    dominantPersona: "Systematic funds",
    dominantAudience: "Funds moving from paper to production with strict risk controls.",
    secondaryAudiences: ["Prop desks scaling automated execution.","Teams replacing brittle scripts with monitored services."],
  },
  "real-time-pnl-exposure-monitoring": {
    dominantPersona: "Risk leads",
    dominantAudience: "Risk and ops leads who need PnL and exposure before the close.",
    secondaryAudiences: ["PMs tracking intraday strategy health.","Engineering teams adding observability to legacy stacks."],
  },
  "trade-analytics-reporting": {
    dominantPersona: "Portfolio managers",
    dominantAudience: "PMs who need slippage and attribution, not vanity Sharpe ratios.",
    secondaryAudiences: ["Quant researchers comparing live vs backtest.","Ops teams reporting to investors weekly."],
  },
  "quant-research-infrastructure": {
    dominantPersona: "Quant research leads",
    dominantAudience: "Research leads tired of non-reproducible notebook experiments.",
    secondaryAudiences: ["Funds standardizing data pipelines.","Teams onboarding new quants faster."],
  },
  "trading-system-audits-consulting": {
    dominantPersona: "CIOs and tech leads",
    dominantAudience: "Leaders who want an independent read on execution and risk gaps.",
    secondaryAudiences: ["Funds pre-investment in trading infra.","Desks after a near-miss incident."],
  },
  "trading-stack-observability-alerting": {
    dominantPersona: "Trading ops",
    dominantAudience: "Ops teams paging humans on latency and fill anomalies, not noise.",
    secondaryAudiences: ["Engineering adding metrics to execution services.","Funds migrating off manual health checks."],
  },
  "tradingview-indicators-automation": {
    dominantPersona: "Discretionary traders",
    dominantAudience: "Traders automating TradingView signals with logging and guardrails.",
    secondaryAudiences: ["Small funds bridging charting to execution.","Teams testing alerts in shadow first."],
  },
  "trading-tech-maintenance-on-call": {
    dominantPersona: "Trading desk leads",
    dominantAudience: "Desks that cannot afford silent failures during market hours.",
    secondaryAudiences: ["Funds without dedicated SRE for trading.","Teams between hires who need coverage."],
  },
};
