/** Auto-generated service page copy. regenerate via scripts/build-service-copy.js */

export const SERVICE_PAGE_COPY = {
  "saas-development": {
    hero: "SaaS Development. Scoped, shipped, signed off.",
    subhead: "We focus on billing, onboarding, and the first paid customer path. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "SaaS Development | Futurebits",
    metaDescription: "SaaS Development by Futurebits: billing, onboarding, and the first paid customer path. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "web-app-development": {
    hero: "Web App Development that holds up under real users.",
    subhead: "We focus on auth, data model, and the flows users hit daily. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Web App Development | Futurebits",
    metaDescription: "Web App Development by Futurebits: auth, data model, and the flows users hit daily. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "custom-software-development": {
    hero: "Custom Software Development that holds up under real users.",
    subhead: "We focus on workflows your off-the-shelf tools cannot model. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Custom Software Development | Futurebits",
    metaDescription: "Custom Software Development by Futurebits: workflows your off-the-shelf tools cannot model. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "mvp-development": {
    hero: "MVP Development that holds up under real users.",
    subhead: "We focus on one testable hypothesis, not a feature wish list. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "MVP Development | Futurebits",
    metaDescription: "MVP Development by Futurebits: one testable hypothesis, not a feature wish list. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "full-stack-development": {
    hero: "Full Stack Development in your repo, with weekly demos.",
    subhead: "We focus on frontend, API, and deploy in one repo. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Full Stack Development | Futurebits",
    metaDescription: "Full Stack Development by Futurebits: frontend, API, and deploy in one repo. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "frontend-development": {
    hero: "Frontend Development. Scoped, shipped, signed off.",
    subhead: "We focus on React UI that matches design and passes Core Web Vitals. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Frontend Development | Futurebits",
    metaDescription: "Frontend Development by Futurebits: React UI that matches design and passes Core Web Vitals. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "backend-development": {
    hero: "Backend Development that holds up under real users.",
    subhead: "We focus on APIs, jobs, and data layers that survive traffic spikes. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Backend Development | Futurebits",
    metaDescription: "Backend Development by Futurebits: APIs, jobs, and data layers that survive traffic spikes. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "api-development": {
    hero: "API Development that holds up under real users.",
    subhead: "We focus on REST or GraphQL contracts your partners can integrate against. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "API Development | Futurebits",
    metaDescription: "API Development by Futurebits: REST or GraphQL contracts your partners can integrate against. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "dashboard-development": {
    hero: "Dashboard Development without the six-month discovery phase.",
    subhead: "We focus on role-aware views on data your team already trusts. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Dashboard Development | Futurebits",
    metaDescription: "Dashboard Development by Futurebits: role-aware views on data your team already trusts. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "admin-panel-development": {
    hero: "Admin Panel Development that holds up under real users.",
    subhead: "We focus on internal ops screens that replace spreadsheet chaos. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Admin Panel Development | Futurebits",
    metaDescription: "Admin Panel Development by Futurebits: internal ops screens that replace spreadsheet chaos. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "client-portal-development": {
    hero: "Client Portal Development without the six-month discovery phase.",
    subhead: "We focus on customer-facing portals with auth and file workflows. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Client Portal Development | Futurebits",
    metaDescription: "Client Portal Development by Futurebits: customer-facing portals with auth and file workflows. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "internal-tool-development": {
    hero: "Internal Tool Development without the six-month discovery phase.",
    subhead: "We focus on ops tools that cut hours off weekly manual work. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Internal Tool Development | Futurebits",
    metaDescription: "Internal Tool Development by Futurebits: ops tools that cut hours off weekly manual work. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "crm-development": {
    hero: "CRM Development that holds up under real users.",
    subhead: "We focus on pipeline views and automations tied to how you actually sell. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "CRM Development | Futurebits",
    metaDescription: "CRM Development by Futurebits: pipeline views and automations tied to how you actually sell. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "marketplace-development": {
    hero: "Marketplace Development that holds up under real users.",
    subhead: "We focus on two-sided flows, payouts, and trust mechanics. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Marketplace Development | Futurebits",
    metaDescription: "Marketplace Development by Futurebits: two-sided flows, payouts, and trust mechanics. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "subscription-platform-development": {
    hero: "Subscription Platform Development without the six-month discovery phase.",
    subhead: "We focus on plans, trials, and upgrade paths in one codebase. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Subscription Platform Development | Futurebits",
    metaDescription: "Subscription Platform Development by Futurebits: plans, trials, and upgrade paths in one codebase. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "workflow-automation-software": {
    hero: "Workflow Automation Software. Scoped, shipped, signed off.",
    subhead: "We focus on repeatable steps your team runs fifty times a week. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Workflow Automation Software | Futurebits",
    metaDescription: "Workflow Automation Software by Futurebits: repeatable steps your team runs fifty times a week. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "reporting-platform-development": {
    hero: "Reporting Platform Development in your repo, with weekly demos.",
    subhead: "We focus on scheduled reports nobody has to rebuild in Excel. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Reporting Platform Development | Futurebits",
    metaDescription: "Reporting Platform Development by Futurebits: scheduled reports nobody has to rebuild in Excel. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "business-process-automation": {
    hero: "Business Process Automation that holds up under real users.",
    subhead: "We focus on handoffs between teams that currently live in email. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Business Process Automation | Futurebits",
    metaDescription: "Business Process Automation by Futurebits: handoffs between teams that currently live in email. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "no-code-to-code-migration": {
    hero: "No-Code to Code Migration without the six-month discovery phase.",
    subhead: "We focus on Bubble or Webflow limits you are hitting at scale. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "No-Code to Code Migration | Futurebits",
    metaDescription: "No-Code to Code Migration by Futurebits: Bubble or Webflow limits you are hitting at scale. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "legacy-software-modernization": {
    hero: "Legacy Software Modernization without the six-month discovery phase.",
    subhead: "We focus on monoliths that are slow to change and scary to deploy. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Legacy Software Modernization | Futurebits",
    metaDescription: "Legacy Software Modernization by Futurebits: monoliths that are slow to change and scary to deploy. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "excel-automation-smart-reporting": {
    hero: "Excel Automation & Smart Reporting. Scoped, shipped, signed off.",
    subhead: "We focus on spreadsheet workflows that eat days every month. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Excel Automation & Smart Reporting | Futurebits",
    metaDescription: "Excel Automation & Smart Reporting by Futurebits: spreadsheet workflows that eat days every month. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-saas-development": {
    hero: "AI SaaS Development that holds up under real users.",
    subhead: "We focus on AI features inside a SaaS product, not a separate demo app. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI SaaS Development | Futurebits",
    metaDescription: "AI SaaS Development by Futurebits: AI features inside a SaaS product, not a separate demo app. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-product-development": {
    hero: "AI Product Development in your repo, with weekly demos.",
    subhead: "We focus on search, recommendations, or agents inside your existing product. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Product Development | Futurebits",
    metaDescription: "AI Product Development by Futurebits: search, recommendations, or agents inside your existing product. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-workflow-automation": {
    hero: "AI Workflow Automation in your repo, with weekly demos.",
    subhead: "We focus on LLM steps in ops pipelines with human review where it matters. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Workflow Automation | Futurebits",
    metaDescription: "AI Workflow Automation by Futurebits: LLM steps in ops pipelines with human review where it matters. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "chatbot-development": {
    hero: "Chatbot Development that holds up under real users.",
    subhead: "We focus on website and support bots with escalation, not infinite intents. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Chatbot Development | Futurebits",
    metaDescription: "Chatbot Development by Futurebits: website and support bots with escalation, not infinite intents. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "rag-application-development": {
    hero: "RAG Application Development that holds up under real users.",
    subhead: "We focus on retrieval pipelines with evals on your real documents. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "RAG Application Development | Futurebits",
    metaDescription: "RAG Application Development by Futurebits: retrieval pipelines with evals on your real documents. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-document-processing": {
    hero: "AI Document Processing in your repo, with weekly demos.",
    subhead: "We focus on PDFs and forms parsed into structured data you can act on. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Document Processing | Futurebits",
    metaDescription: "AI Document Processing by Futurebits: PDFs and forms parsed into structured data you can act on. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-search-systems": {
    hero: "AI Search Systems without the six-month discovery phase.",
    subhead: "We focus on semantic search over product docs, tickets, or catalog data. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Search Systems | Futurebits",
    metaDescription: "AI Search Systems by Futurebits: semantic search over product docs, tickets, or catalog data. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-recommendation-systems": {
    hero: "AI Recommendation Systems without the six-month discovery phase.",
    subhead: "We focus on ranking that uses your data, not generic collaborative filtering. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Recommendation Systems | Futurebits",
    metaDescription: "AI Recommendation Systems by Futurebits: ranking that uses your data, not generic collaborative filtering. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-agents-development": {
    hero: "AI Agents Development without the six-month discovery phase.",
    subhead: "We focus on agents for sales prep, support triage, or internal ops. scoped. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Agents Development | Futurebits",
    metaDescription: "AI Agents Development by Futurebits: agents for sales prep, support triage, or internal ops. scoped. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "llm-integration": {
    hero: "LLM Integration that holds up under real users.",
    subhead: "We focus on summarization, classification, or generation inside your app. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "LLM Integration | Futurebits",
    metaDescription: "LLM Integration by Futurebits: summarization, classification, or generation inside your app. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "openai-api-integration": {
    hero: "OpenAI API Integration in your repo, with weekly demos.",
    subhead: "We focus on OpenAI calls with fallbacks, logging, and cost controls. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "OpenAI API Integration | Futurebits",
    metaDescription: "OpenAI API Integration by Futurebits: OpenAI calls with fallbacks, logging, and cost controls. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "custom-ai-tools": {
    hero: "Custom AI Tools that holds up under real users.",
    subhead: "We focus on internal tools your team asks for in Slack every week. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Custom AI Tools | Futurebits",
    metaDescription: "Custom AI Tools by Futurebits: internal tools your team asks for in Slack every week. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-dashboard-development": {
    hero: "AI Dashboard Development. Scoped, shipped, signed off.",
    subhead: "We focus on dashboards that surface model quality and usage, not vanity charts. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Dashboard Development | Futurebits",
    metaDescription: "AI Dashboard Development by Futurebits: dashboards that surface model quality and usage, not vanity charts. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-data-extraction": {
    hero: "AI-Based Data Extraction in your repo, with weekly demos.",
    subhead: "We focus on unstructured inputs turned into JSON your systems can ingest. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI-Based Data Extraction | Futurebits",
    metaDescription: "AI-Based Data Extraction by Futurebits: unstructured inputs turned into JSON your systems can ingest. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-customer-support-tools": {
    hero: "AI Customer Support Tools without the six-month discovery phase.",
    subhead: "We focus on deflection on top-20 tickets with Zendesk or Intercom handoff. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Customer Support Tools | Futurebits",
    metaDescription: "AI Customer Support Tools by Futurebits: deflection on top-20 tickets with Zendesk or Intercom handoff. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "custom-gpt-knowledge-base": {
    hero: "Custom GPT & Knowledge Base Solutions without the six-month discovery phase.",
    subhead: "We focus on Custom GPTs grounded in your policies and product docs. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Custom GPT & Knowledge Base Solutions | Futurebits",
    metaDescription: "Custom GPT & Knowledge Base Solutions by Futurebits: Custom GPTs grounded in your policies and product docs. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-content-generation": {
    hero: "AI Content Generation Systems without the six-month discovery phase.",
    subhead: "We focus on marketing copy pipelines with tone and fact-check gates. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Content Generation Systems | Futurebits",
    metaDescription: "AI Content Generation Systems by Futurebits: marketing copy pipelines with tone and fact-check gates. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ai-video-generation": {
    hero: "AI Video Generation that holds up under real users.",
    subhead: "We focus on templated video output for social and ads. brand-locked. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "AI Video Generation | Futurebits",
    metaDescription: "AI Video Generation by Futurebits: templated video output for social and ads. brand-locked. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ui-ux-design": {
    hero: "UI/UX Design. Scoped, shipped, signed off.",
    subhead: "We focus on flows where users drop off, not decorative screen refreshes. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "UI/UX Design | Futurebits",
    metaDescription: "UI/UX Design by Futurebits: flows where users drop off, not decorative screen refreshes. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "product-design": {
    hero: "Product Design in your repo, with weekly demos.",
    subhead: "We focus on problem framing through shipped UI in Figma and code. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Product Design | Futurebits",
    metaDescription: "Product Design by Futurebits: problem framing through shipped UI in Figma and code. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "web-app-design": {
    hero: "Web App Design in your repo, with weekly demos.",
    subhead: "We focus on web product UI that engineers can build from components. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Web App Design | Futurebits",
    metaDescription: "Web App Design by Futurebits: web product UI that engineers can build from components. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "saas-ui-design": {
    hero: "SaaS UI Design in your repo, with weekly demos.",
    subhead: "We focus on SaaS patterns for onboarding, settings, and billing screens. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "SaaS UI Design | Futurebits",
    metaDescription: "SaaS UI Design by Futurebits: SaaS patterns for onboarding, settings, and billing screens. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "dashboard-ui-design": {
    hero: "Dashboard UI Design that holds up under real users.",
    subhead: "We focus on dense data views that stay scannable on a laptop. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Dashboard UI Design | Futurebits",
    metaDescription: "Dashboard UI Design by Futurebits: dense data views that stay scannable on a laptop. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "design-systems": {
    hero: "Design Systems in your repo, with weekly demos.",
    subhead: "We focus on 10–15 components your team reuses, not a 200-component library day one. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Design Systems | Futurebits",
    metaDescription: "Design Systems by Futurebits: 10–15 components your team reuses, not a 200-component library day one. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "wireframing": {
    hero: "Wireframing that holds up under real users.",
    subhead: "We focus on clickable flows before engineering commits to architecture. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Wireframing | Futurebits",
    metaDescription: "Wireframing by Futurebits: clickable flows before engineering commits to architecture. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "prototyping": {
    hero: "Prototyping that holds up under real users.",
    subhead: "We focus on interactive prototypes for stakeholder and user testing. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Prototyping | Futurebits",
    metaDescription: "Prototyping by Futurebits: interactive prototypes for stakeholder and user testing. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "landing-page-design": {
    hero: "Landing Page Design that holds up under real users.",
    subhead: "We focus on landing pages matched to your acquisition channel. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Landing Page Design | Futurebits",
    metaDescription: "Landing Page Design by Futurebits: landing pages matched to your acquisition channel. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "mobile-app-ui-design": {
    hero: "Mobile App UI Design. Scoped, shipped, signed off.",
    subhead: "We focus on touch-first UI for iOS, Android, or responsive web. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Mobile App UI Design | Futurebits",
    metaDescription: "Mobile App UI Design by Futurebits: touch-first UI for iOS, Android, or responsive web. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "user-flow-design": {
    hero: "User Flow Design. Scoped, shipped, signed off.",
    subhead: "We focus on signup-to-activation paths with fewer steps. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "User Flow Design | Futurebits",
    metaDescription: "User Flow Design by Futurebits: signup-to-activation paths with fewer steps. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "figma-design": {
    hero: "Figma Design. Scoped, shipped, signed off.",
    subhead: "We focus on Figma files organized for handoff, not presentation decks. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Figma Design | Futurebits",
    metaDescription: "Figma Design by Futurebits: Figma files organized for handoff, not presentation decks. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "website-ux-audit": {
    hero: "Website UX Audit & Product Experience Audit. Scoped, shipped, signed off.",
    subhead: "We focus on conversion blockers on high-intent pages. ranked by impact. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Website UX Audit & Product Experience Audit | Futurebits",
    metaDescription: "Website UX Audit & Product Experience Audit by Futurebits: conversion blockers on high-intent pages. ranked by impact. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "ux-research": {
    hero: "UX Research that holds up under real users.",
    subhead: "We focus on five interviews that answer one product decision. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "UX Research | Futurebits",
    metaDescription: "UX Research by Futurebits: five interviews that answer one product decision. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "branding-visual-identity": {
    hero: "Branding & Visual Identity. Scoped, shipped, signed off.",
    subhead: "We focus on logo, type, and color that work in product UI and marketing, not decks alone. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Branding & Visual Identity | Futurebits",
    metaDescription: "Branding & Visual Identity by Futurebits: logo, type, and color that work in product UI and marketing, not decks alone. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "data-visualization-design": {
    hero: "Data Visualization Design without the six-month discovery phase.",
    subhead: "We focus on charts and dashboards that change what teams do Monday morning. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Data Visualization Design | Futurebits",
    metaDescription: "Data Visualization Design by Futurebits: charts and dashboards that change what teams do Monday morning. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "strategy-backtesting": {
    hero: "Strategy Backtesting. Scoped, shipped, signed off.",
    subhead: "We focus on backtests with fees, slippage, and fill logic you can defend. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Strategy Backtesting | Futurebits",
    metaDescription: "Strategy Backtesting by Futurebits: backtests with fees, slippage, and fill logic you can defend. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "forward-testing-shadow-mode": {
    hero: "Forward Testing and Shadow Mode that holds up under real users.",
    subhead: "We focus on paper and shadow runs before real capital. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Forward Testing & Shadow Mode | Futurebits",
    metaDescription: "Forward Testing & Shadow Mode by Futurebits: paper and shadow runs before real capital. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "live-trading-execution-systems": {
    hero: "Live Trading Execution Systems in your repo, with weekly demos.",
    subhead: "We focus on order lifecycle, retries, and kill switches in prod. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Live Trading Execution Systems | Futurebits",
    metaDescription: "Live Trading Execution Systems by Futurebits: order lifecycle, retries, and kill switches in prod. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "real-time-pnl-exposure-monitoring": {
    hero: "Real-Time PnL & Exposure Monitoring without the six-month discovery phase.",
    subhead: "We focus on PnL and exposure alerts before small issues compound. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Real-Time PnL & Exposure Monitoring | Futurebits",
    metaDescription: "Real-Time PnL & Exposure Monitoring by Futurebits: PnL and exposure alerts before small issues compound. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "trade-analytics-reporting": {
    hero: "Trade Analytics & Reporting without the six-month discovery phase.",
    subhead: "We focus on slippage and attribution reports your PM actually reads. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Trade Analytics & Reporting | Futurebits",
    metaDescription: "Trade Analytics & Reporting by Futurebits: slippage and attribution reports your PM actually reads. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "quant-research-infrastructure": {
    hero: "Quant Research Infrastructure without the six-month discovery phase.",
    subhead: "We focus on research pipelines that reproduce, not one-off notebooks. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Quant Research Infrastructure | Futurebits",
    metaDescription: "Quant Research Infrastructure by Futurebits: research pipelines that reproduce, not one-off notebooks. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "trading-system-audits-consulting": {
    hero: "Trading System Audits & Consulting. Scoped, shipped, signed off.",
    subhead: "We focus on architecture and risk review with a fix list owners can execute. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Trading System Audits & Consulting | Futurebits",
    metaDescription: "Trading System Audits & Consulting by Futurebits: architecture and risk review with a fix list owners can execute. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "trading-stack-observability-alerting": {
    hero: "Trading Stack Observability & Alerting. Scoped, shipped, signed off.",
    subhead: "We focus on latency, fills, and health metrics with on-call runbooks. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Trading Stack Observability & Alerting | Futurebits",
    metaDescription: "Trading Stack Observability & Alerting by Futurebits: latency, fills, and health metrics with on-call runbooks. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "tradingview-indicators-automation": {
    hero: "TradingView Indicators & Automation without the six-month discovery phase.",
    subhead: "We focus on TradingView alerts wired to execution or logging safely. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "TradingView Indicators & Automation | Futurebits",
    metaDescription: "TradingView Indicators & Automation by Futurebits: TradingView alerts wired to execution or logging safely. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "trading-tech-maintenance-on-call": {
    hero: "Trading Tech Maintenance & On-Call. Scoped, shipped, signed off.",
    subhead: "We focus on on-call for trading infra without hero engineers. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Trading Tech Maintenance & On-Call | Futurebits",
    metaDescription: "Trading Tech Maintenance & On-Call by Futurebits: on-call for trading infra without hero engineers. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "payment-gateway-integration": {
    hero: "Payment Gateway Integration that holds up under real users.",
    subhead: "We focus on checkout flows with reconciliation and error handling. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Payment Gateway Integration | Futurebits",
    metaDescription: "Payment Gateway Integration by Futurebits: checkout flows with reconciliation and error handling. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "stripe-integration": {
    hero: "Stripe Integration in your repo, with weekly demos.",
    subhead: "We focus on Stripe checkout, webhooks, and idempotent handlers. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Stripe Integration | Futurebits",
    metaDescription: "Stripe Integration by Futurebits: Stripe checkout, webhooks, and idempotent handlers. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "razorpay-integration": {
    hero: "Razorpay Integration. Scoped, shipped, signed off.",
    subhead: "We focus on Razorpay for India. subscriptions and webhooks included. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Razorpay Integration | Futurebits",
    metaDescription: "Razorpay Integration by Futurebits: Razorpay for India. subscriptions and webhooks included. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "subscription-billing-setup": {
    hero: "Subscription Billing Setup in your repo, with weekly demos.",
    subhead: "We focus on plans, proration, dunning, and finance-visible reporting. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Subscription Billing Setup | Futurebits",
    metaDescription: "Subscription Billing Setup by Futurebits: plans, proration, dunning, and finance-visible reporting. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "crm-integration": {
    hero: "CRM Integration that holds up under real users.",
    subhead: "We focus on CRM and product data in sync, not duplicate manual entry. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "CRM Integration | Futurebits",
    metaDescription: "CRM Integration by Futurebits: CRM and product data in sync, not duplicate manual entry. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "whatsapp-api-integration": {
    hero: "WhatsApp API Integration. Scoped, shipped, signed off.",
    subhead: "We focus on WhatsApp Business API for notifications and support. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "WhatsApp API Integration | Futurebits",
    metaDescription: "WhatsApp API Integration by Futurebits: WhatsApp Business API for notifications and support. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "email-automation-integration": {
    hero: "Email Automation Integration. Scoped, shipped, signed off.",
    subhead: "We focus on Resend, SendGrid, or Customer.io wired to product events. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Email Automation Integration | Futurebits",
    metaDescription: "Email Automation Integration by Futurebits: Resend, SendGrid, or Customer.io wired to product events. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "google-analytics-setup": {
    hero: "Google Analytics Setup in your repo, with weekly demos.",
    subhead: "We focus on GA4 events that match product metrics, not default pageviews only. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Google Analytics Setup | Futurebits",
    metaDescription: "Google Analytics Setup by Futurebits: GA4 events that match product metrics, not default pageviews only. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "cms-integration": {
    hero: "CMS Integration that holds up under real users.",
    subhead: "We focus on headless CMS content in your Next.js or React app. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "CMS Integration | Futurebits",
    metaDescription: "CMS Integration by Futurebits: headless CMS content in your Next.js or React app. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "third-party-api-integration": {
    hero: "Third-Party API Integration that holds up under real users.",
    subhead: "We focus on vendor APIs with retries, rate limits, and monitoring. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Third-Party API Integration | Futurebits",
    metaDescription: "Third-Party API Integration by Futurebits: vendor APIs with retries, rate limits, and monitoring. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "authentication-setup": {
    hero: "Authentication Setup. Scoped, shipped, signed off.",
    subhead: "We focus on Auth0, Clerk, or Supabase Auth with RBAC basics. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Authentication Setup | Futurebits",
    metaDescription: "Authentication Setup by Futurebits: Auth0, Clerk, or Supabase Auth with RBAC basics. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "role-based-access-control": {
    hero: "Role-Based Access Control without the six-month discovery phase.",
    subhead: "We focus on roles and permissions that match how your org actually works. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Role-Based Access Control | Futurebits",
    metaDescription: "Role-Based Access Control by Futurebits: roles and permissions that match how your org actually works. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "database-setup": {
    hero: "Database Setup in your repo, with weekly demos.",
    subhead: "We focus on Postgres or Supabase schema, migrations, and backup basics. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Database Setup | Futurebits",
    metaDescription: "Database Setup by Futurebits: Postgres or Supabase schema, migrations, and backup basics. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "cloud-deployment": {
    hero: "Cloud Deployment. Scoped, shipped, signed off.",
    subhead: "We focus on Vercel, AWS, or Railway deploy with env and CI wired. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Cloud Deployment | Futurebits",
    metaDescription: "Cloud Deployment by Futurebits: Vercel, AWS, or Railway deploy with env and CI wired. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "startup-mvp": {
    hero: "Startup MVP that holds up under real users.",
    subhead: "We focus on first release that tests one business hypothesis. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Startup MVP | Futurebits",
    metaDescription: "Startup MVP by Futurebits: first release that tests one business hypothesis. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "founder-tech-partner": {
    hero: "Founder Tech Partner. Scoped, shipped, signed off.",
    subhead: "We focus on technical decisions when you do not have a CTO yet. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Founder Tech Partner | Futurebits",
    metaDescription: "Founder Tech Partner by Futurebits: technical decisions when you do not have a CTO yet. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "product-strategy": {
    hero: "Product Strategy. Scoped, shipped, signed off.",
    subhead: "We focus on what to build first. ranked by revenue impact. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Product Strategy | Futurebits",
    metaDescription: "Product Strategy by Futurebits: what to build first. ranked by revenue impact. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "product-consulting": {
    hero: "Product Consulting in your repo, with weekly demos.",
    subhead: "We focus on roadmap and scope review before you hire or spend. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Product Consulting | Futurebits",
    metaDescription: "Product Consulting by Futurebits: roadmap and scope review before you hire or spend. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "tech-consulting": {
    hero: "Tech Consulting that holds up under real users.",
    subhead: "We focus on architecture choices without a six-week assessment deck. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Tech Consulting | Futurebits",
    metaDescription: "Tech Consulting by Futurebits: architecture choices without a six-week assessment deck. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "saas-launch-partner": {
    hero: "SaaS Launch Partner that holds up under real users.",
    subhead: "We focus on launch checklist: billing, analytics, and onboarding live. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "SaaS Launch Partner | Futurebits",
    metaDescription: "SaaS Launch Partner by Futurebits: launch checklist: billing, analytics, and onboarding live. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "prototype-to-product": {
    hero: "Prototype to Product. Scoped, shipped, signed off.",
    subhead: "We focus on prototype hardened for real users and real data. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Prototype to Product | Futurebits",
    metaDescription: "Prototype to Product by Futurebits: prototype hardened for real users and real data. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "idea-to-mvp": {
    hero: "Idea to MVP that holds up under real users.",
    subhead: "We focus on idea to working software in weeks. scope written first. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Idea to MVP | Futurebits",
    metaDescription: "Idea to MVP by Futurebits: idea to working software in weeks. scope written first. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "product-roadmap-planning": {
    hero: "Product Roadmap Planning. Scoped, shipped, signed off.",
    subhead: "We focus on roadmap your team can execute, not a 40-item wish list. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Product Roadmap Planning | Futurebits",
    metaDescription: "Product Roadmap Planning by Futurebits: roadmap your team can execute, not a 40-item wish list. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "software-architecture-planning": {
    hero: "Software Architecture Planning in your repo, with weekly demos.",
    subhead: "We focus on architecture doc your first three hires can follow. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "Software Architecture Planning | Futurebits",
    metaDescription: "Software Architecture Planning by Futurebits: architecture doc your first three hires can follow. Fixed-scope sprints, direct team access, ship in your repo.",
  },
  "end-to-end-product-design-development": {
    hero: "End-to-End Product Design & Development without the six-month discovery phase.",
    subhead: "We focus on design and engineering in one team. one repo. Written scope, your stack, weekly demos. No account-manager layer.",
    metaTitle: "End-to-End Product Design & Development | Futurebits",
    metaDescription: "End-to-End Product Design & Development by Futurebits: design and engineering in one team. one repo. Fixed-scope sprints, direct team access, ship in your repo.",
  },
};

export const MARKETS_AUDIENCE = {
  "strategy-backtesting": {
    dominantPersona: "Quant funds",
    dominantAudience: "Quant funds validating signal stability before allocation reviews.",
    secondaryAudiences: ["Prop desks testing variants across regimes.","Discretionary teams codifying playbooks into testable systems."],
  },
  "forward-testing-shadow-mode": {
    dominantPersona: "Prop desks",
    dominantAudience: "Prop desks pressure-testing intraday systems before desk capital.",
    secondaryAudiences: ["Funds with strict research-to-production gates.","Desks validating model overlays alongside manual execution."],
  },
  "live-trading-execution-systems": {
    dominantPersona: "Systematic funds",
    dominantAudience: "Funds moving from paper to production with strict risk controls.",
    secondaryAudiences: ["Prop desks scaling automated execution.","Teams replacing brittle scripts with monitored services."],
  },
  "real-time-pnl-exposure-monitoring": {
    dominantPersona: "Risk leads",
    dominantAudience: "Risk and ops leads who need PnL and exposure before the close.",
    secondaryAudiences: ["PMs tracking intraday strategy health.","Engineering teams adding observability to legacy stacks."],
  },
  "trade-analytics-reporting": {
    dominantPersona: "Portfolio managers",
    dominantAudience: "PMs who need slippage and attribution, not vanity Sharpe ratios.",
    secondaryAudiences: ["Quant researchers comparing live vs backtest.","Ops teams reporting to investors weekly."],
  },
  "quant-research-infrastructure": {
    dominantPersona: "Quant research leads",
    dominantAudience: "Research leads tired of non-reproducible notebook experiments.",
    secondaryAudiences: ["Funds standardizing data pipelines.","Teams onboarding new quants faster."],
  },
  "trading-system-audits-consulting": {
    dominantPersona: "CIOs and tech leads",
    dominantAudience: "Leaders who want an independent read on execution and risk gaps.",
    secondaryAudiences: ["Funds pre-investment in trading infra.","Desks after a near-miss incident."],
  },
  "trading-stack-observability-alerting": {
    dominantPersona: "Trading ops",
    dominantAudience: "Ops teams paging humans on latency and fill anomalies, not noise.",
    secondaryAudiences: ["Engineering adding metrics to execution services.","Funds migrating off manual health checks."],
  },
  "tradingview-indicators-automation": {
    dominantPersona: "Discretionary traders",
    dominantAudience: "Traders automating TradingView signals with logging and guardrails.",
    secondaryAudiences: ["Small funds bridging charting to execution.","Teams testing alerts in shadow first."],
  },
  "trading-tech-maintenance-on-call": {
    dominantPersona: "Trading desk leads",
    dominantAudience: "Desks that cannot afford silent failures during market hours.",
    secondaryAudiences: ["Funds without dedicated SRE for trading.","Teams between hires who need coverage."],
  },
};
